name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies on frontend
        run: cd frontend && npm install --force
      - name: Build
        run: cd frontend && npm run build --if-present
      - name: Install dependencies on backend
        run: cd backend && npm install
      - name: Build
        run: cd backend npm && run build --if-present

